// <auto-generated />
namespace WebAPIDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version11_AddedLandline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version11_AddedLandline));
        
        string IMigrationMetadata.Id
        {
            get { return "202010120606049_Version1.1_AddedLandline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
